---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
#  namespace: pg
  name: pg-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "pg-pv"
  storageClassName: ""

