---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: prom-pvc
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: "prom-pv"
  storageClassName: ""

