---
kind: Service
apiVersion: v1
metadata:
  name: prom-srv
  labels:
    app: prometheus
spec:
  clusterIP: None
  ports:
    - name: srv
      protocol: TCP
      port: 9090
  selector:
    app: prometheus
