---
apiVersion: v1
kind: ReplicationController
metadata:
  name: pg-rc
  namespace: pg
spec:
  replicas: 1
  selector:
    app: pg
  template:
    metadata:
      name: pg
      labels:
        app: pg
    spec:
      containers:
      - image: postgres:10.13
        name: pg
        ports:
          - protocol: TCP
            containerPort: 5432
            name: pg
        volumeMounts:
        - name: pg-pvc
          mountPath: /var/lib/postgresql/data
      restartPolicy: Always
      volumes:
      - name: pg-pvc
        persistentVolumeClaim:
          claimName: pg-pvc