---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pg-rs
  namespace: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
      - image: postgres:10.13
        name: pg
        ports:
        - protocol: TCP
          containerPort: 5432
          name: pg
